//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsAppDemo.DOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserRoleMaps = new HashSet<UserRoleMap>();
            this.RoleMenuMaps = new HashSet<RoleMenuMap>();
        }
    
        public int ID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<UserRoleMap> UserRoleMaps { get; set; }
        public virtual ICollection<RoleMenuMap> RoleMenuMaps { get; set; }
    }
}
