//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsAppDemo.DOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRoleMaps = new HashSet<UserRoleMap>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<UserRoleMap> UserRoleMaps { get; set; }
    }
}
